name: CI

on: [pull_request]

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run start-local &
    - run: sleep 30
    - run: npx playwright install
    - run: npm run playwright
    - run: ls
    - uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshot.png